# -*- coding: utf-8 -*-
"""Car Prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZTWky0tJZJulpYTioXjzXjhjhztpQTye
"""

# ============================================================
#   CAR PRICE PREDICTION - Complete ML Project
#   Algorithms: Linear Regression, Multiple Linear Regression,
#               Logistic Regression, Non-Linear Regression,
#               Naive Bayes, Decision Tree, KNN
#   Dataset: car_data.csv (from Kaggle)
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import (mean_absolute_error, mean_squared_error,
                             r2_score, accuracy_score, classification_report,
                             confusion_matrix)

# Regression Models
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.neighbors import KNeighborsRegressor, KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

import pickle


# ============================================================
# STEP 1: LOAD DATASET
# ============================================================
print("=" * 60)
print("STEP 1: LOADING DATASET")
print("=" * 60)

# ----------------------------------------------------------
# HOW TO UPLOAD DATA:
# Place 'car_data.csv' in the SAME FOLDER as this Python file.
# Download from: https://www.kaggle.com/datasets/vijayaadithyanvg/car-price-predictionused-cars
# ----------------------------------------------------------

df = pd.read_csv('../data/car_data.csv')

print(f"Dataset Shape: {df.shape}")
print(f"\nFirst 5 Rows:\n{df.head()}")
print(f"\nColumn Names: {list(df.columns)}")
print(f"\nData Types:\n{df.dtypes}")
print(f"\nMissing Values:\n{df.isnull().sum()}")
print(f"\nBasic Statistics:\n{df.describe()}")


# ============================================================
# STEP 2: DATA PREPROCESSING
# ============================================================

print("\n" + "=" * 60)
print("STEP 2: DATA PREPROCESSING")
print("=" * 60)

# Drop Car_Name column
if 'Car_Name' in df.columns:
    df.drop(columns=['Car_Name'], inplace=True)

# Create Car_Age feature
current_year = 2024

if 'Year' in df.columns:
    df['Car_Age'] = current_year - df['Year']
    df.drop(columns=['Year'], inplace=True)

# Remove duplicates
before = df.shape[0]

df.drop_duplicates(inplace=True)

print(f"Removed {before - df.shape[0]} duplicate rows")

# Remove missing values
df.dropna(inplace=True)

print(f"Dataset after cleaning: {df.shape}")

# ============================================================
# ENCODE ALL CATEGORICAL COLUMNS
# ============================================================

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

# Automatically detect text columns
categorical_cols = df.select_dtypes(include=['object']).columns

print("\nCategorical Columns:", list(categorical_cols))

# Convert text columns into numbers
for col in categorical_cols:
    df[col] = le.fit_transform(df[col])
    print(f"Encoded '{col}'")

print("\nPreprocessed Data Sample:")
print(df.head())


# ============================================================
# STEP 3: DEFINE FEATURES AND TARGET
# ============================================================

print("\n" + "=" * 60)
print("STEP 3: FEATURE & TARGET DEFINITION")
print("=" * 60)

# CHECK COLUMN NAMES
print("\nDataset Columns:")
print(df.columns)

# TARGET COLUMN
target_col = 'Selling_Price'

# Features and Target
X = df.drop(columns=[target_col])

y = df[target_col]

print(f"\nFeatures (X): {list(X.columns)}")

print(f"\nTarget (y): {target_col}")

print(f"\nX shape: {X.shape}")

print(f"y shape: {y.shape}")

# ============================================================
# STEP 4: FEATURE SCALING
# ============================================================
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Save scaler for API use
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)
print("\nScaler saved as scaler.pkl")


# ============================================================
# STEP 5: TRAIN/TEST SPLIT (80% Train, 20% Test)
# ============================================================
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)
print(f"\nTraining size: {X_train.shape[0]} rows")
print(f"Testing size:  {X_test.shape[0]} rows")


# ============================================================
# STEP 6: TRAIN ALL MODELS
# ============================================================
print("\n" + "=" * 60)
print("STEP 6: MODEL TRAINING")
print("=" * 60)

models = {
    # 1. Simple Linear Regression (using only 1 feature: Present_Price)
    "1. Simple Linear Regression": LinearRegression(),

    # 2. Multiple Linear Regression (all features)
    "2. Multiple Linear Regression": LinearRegression(),

    # 3. Ridge Regression (Non-linear regularization)
    "3. Ridge Regression (Non-Linear)": Ridge(alpha=1.0),

    # 4. Lasso Regression
    "4. Lasso Regression": Lasso(alpha=0.1),

    # 5. Decision Tree Regressor
    "5. Decision Tree": DecisionTreeRegressor(max_depth=6, random_state=42),

    # 6. K-Nearest Neighbors
    "6. KNN": KNeighborsRegressor(n_neighbors=5),

    # 7. Random Forest
    "7. Random Forest": RandomForestRegressor(n_estimators=100, random_state=42),

    # 8. Gradient Boosting
    "8. Gradient Boosting": GradientBoostingRegressor(n_estimators=100, random_state=42),

    # 9. SVR
    "9. SVR": SVR(kernel='rbf'),
}

results = {}

for name, model in models.items():
    if name == "1. Simple Linear Regression":
        # Use only 1 feature (index 0 = Present_Price after encoding)
        X_tr_simple = X_train[:, 0].reshape(-1, 1)
        X_te_simple = X_test[:, 0].reshape(-1, 1)
        model.fit(X_tr_simple, y_train)
        y_pred = model.predict(X_te_simple)
    else:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

    mae  = mean_absolute_error(y_test, y_pred)
    mse  = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2   = r2_score(y_test, y_pred)

    results[name] = {
        'model':  model,
        'y_pred': y_pred,
        'MAE':    round(mae, 4),
        'MSE':    round(mse, 4),
        'RMSE':   round(rmse, 4),
        'R2':     round(r2, 4),
    }
    print(f"\n{name}")
    print(f"  MAE={mae:.4f}  RMSE={rmse:.4f}  R²={r2:.4f}")


# ============================================================
# STEP 7: NAIVE BAYES (Classification Version)
# ============================================================
print("\n" + "=" * 60)
print("STEP 7: NAIVE BAYES (Classified Price Ranges)")
print("=" * 60)

# Convert price to categories for Naive Bayes (classification only)
bins   = [0, 3, 7, 15, 100]
labels = ['Low', 'Medium', 'High', 'Luxury']
y_cat  = pd.cut(y, bins=bins, labels=labels)
y_cat_encoded = LabelEncoder().fit_transform(y_cat)

X_tr_nb, X_te_nb, y_tr_nb, y_te_nb = train_test_split(
    X_scaled, y_cat_encoded, test_size=0.2, random_state=42
)

nb_model = GaussianNB()
nb_model.fit(X_tr_nb, y_tr_nb)
y_pred_nb = nb_model.predict(X_te_nb)

nb_acc = accuracy_score(y_te_nb, y_pred_nb)
print(f"Naive Bayes Accuracy: {nb_acc * 100:.2f}%")
print(f"\nClassification Report:\n{classification_report(y_te_nb, y_pred_nb, target_names=labels)}")

# Save NB for confusion matrix
results['10. Naive Bayes (Classification)'] = {
    'model': nb_model,
    'y_pred_nb': y_pred_nb,
    'accuracy': round(nb_acc * 100, 2)
}


# ============================================================
# STEP 8: LOGISTIC REGRESSION (Classification Version)
# ============================================================
print("\n" + "=" * 60)
print("STEP 8: LOGISTIC REGRESSION (Price Category Classification)")
print("=" * 60)

from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(max_iter=1000, random_state=42)
lr_model.fit(X_tr_nb, y_tr_nb)
y_pred_lr = lr_model.predict(X_te_nb)

lr_acc = accuracy_score(y_te_nb, y_pred_lr)
print(f"Logistic Regression Accuracy: {lr_acc * 100:.2f}%")
print(f"\nClassification Report:\n{classification_report(y_te_nb, y_pred_lr, target_names=labels)}")

results['11. Logistic Regression (Classification)'] = {
    'model':    lr_model,
    'y_pred_lr': y_pred_lr,
    'accuracy': round(lr_acc * 100, 2)
}


# ============================================================
# STEP 9: RESULTS SUMMARY TABLE
# ============================================================
print("\n" + "=" * 60)
print("STEP 9: RESULTS SUMMARY (Regression Models)")
print("=" * 60)

summary_rows = []
for name, res in results.items():
    if 'R2' in res:
        summary_rows.append({
            'Model':  name,
            'MAE':    res['MAE'],
            'RMSE':   res['RMSE'],
            'R2':     res['R2'],
        })

summary_df = pd.DataFrame(summary_rows).sort_values('R2', ascending=False)
print(summary_df.to_string(index=False))


# ============================================================
# STEP 10: BEST MODEL SELECTION
# ============================================================
print("\n" + "=" * 60)
print("STEP 10: BEST MODEL SELECTION")
print("=" * 60)

best_row  = summary_df.iloc[0]
best_name = best_row['Model']
best_model_obj = results[best_name]['model']

print(f"Best Model: {best_name}")
print(f"R² Score  : {best_row['R2']}")
print(f"RMSE      : {best_row['RMSE']}")
print(f"MAE       : {best_row['MAE']}")

# Save best model
with open('best_model.pkl', 'wb') as f:
    pickle.dump(best_model_obj, f)
print("\n✅ best_model.pkl saved successfully!")


# ============================================================
# STEP 11: GRAPHICAL ANALYSIS
# ============================================================
print("\n" + "=" * 60)
print("STEP 11: GRAPHICAL ANALYSIS")
print("=" * 60)

fig, axes = plt.subplots(2, 3, figsize=(18, 12))
fig.suptitle('Car Price Prediction - Model Evaluation Graphs', fontsize=16, fontweight='bold')

# --- Graph 1: R² Score Comparison ---
ax1 = axes[0, 0]
r2_data = [(n, r['R2']) for n, r in results.items() if 'R2' in r]
r2_data.sort(key=lambda x: x[1])
names_r2 = [x[0].split('. ')[1] if '. ' in x[0] else x[0] for x in r2_data]
vals_r2  = [x[1] for x in r2_data]
colors_r2 = ['#e74c3c' if v < 0.7 else '#f39c12' if v < 0.85 else '#27ae60' for v in vals_r2]
bars = ax1.barh(names_r2, vals_r2, color=colors_r2, edgecolor='white', linewidth=0.5)
ax1.set_xlabel('R² Score')
ax1.set_title('R² Score Comparison (All Models)', fontweight='bold')
ax1.set_xlim(0, 1.05)
for bar, val in zip(bars, vals_r2):
    ax1.text(bar.get_width() + 0.01, bar.get_y() + bar.get_height()/2,
             f'{val:.3f}', va='center', fontsize=8)
ax1.axvline(x=0.9, color='blue', linestyle='--', alpha=0.5, label='90% target')
ax1.legend(fontsize=8)

# --- Graph 2: RMSE Comparison ---
ax2 = axes[0, 1]
rmse_data = [(n, r['RMSE']) for n, r in results.items() if 'RMSE' in r]
names_rmse = [x[0].split('. ')[1] if '. ' in x[0] else x[0] for x in rmse_data]
vals_rmse  = [x[1] for x in rmse_data]
ax2.bar(range(len(names_rmse)), vals_rmse, color='#3498db', edgecolor='white')
ax2.set_xticks(range(len(names_rmse)))
ax2.set_xticklabels(names_rmse, rotation=45, ha='right', fontsize=7)
ax2.set_ylabel('RMSE (Lakhs)')
ax2.set_title('RMSE Comparison', fontweight='bold')
for i, v in enumerate(vals_rmse):
    ax2.text(i, v + 0.02, f'{v:.2f}', ha='center', fontsize=7)

# --- Graph 3: Actual vs Predicted (Best Model) ---
ax3 = axes[0, 2]
best_preds = results[best_name]['y_pred']
ax3.scatter(y_test, best_preds, alpha=0.6, color='#9b59b6', s=30, label='Predictions')
min_val = min(y_test.min(), best_preds.min())
max_val = max(y_test.max(), best_preds.max())
ax3.plot([min_val, max_val], [min_val, max_val], 'r--', lw=2, label='Perfect Fit')
ax3.set_xlabel('Actual Price (Lakhs)')
ax3.set_ylabel('Predicted Price (Lakhs)')
ax3.set_title(f'Actual vs Predicted\n({best_name.split(". ")[1]})', fontweight='bold')
ax3.legend()

# --- Graph 4: Residual Plot ---
ax4 = axes[1, 0]
residuals = y_test.values - best_preds
ax4.scatter(best_preds, residuals, alpha=0.6, color='#e67e22', s=30)
ax4.axhline(y=0, color='red', linestyle='--', lw=2)
ax4.set_xlabel('Predicted Price')
ax4.set_ylabel('Residuals')
ax4.set_title('Residual Plot (Best Model)', fontweight='bold')

# --- Graph 5: Error Distribution ---
ax5 = axes[1, 1]
ax5.hist(residuals, bins=25, color='#1abc9c', edgecolor='white', alpha=0.8)
ax5.axvline(x=0, color='red', linestyle='--', lw=2, label='Zero Error')
ax5.set_xlabel('Residual Value')
ax5.set_ylabel('Frequency')
ax5.set_title('Error Distribution', fontweight='bold')
ax5.legend()

# --- Graph 6: Naive Bayes & Logistic Regression Confusion Matrix ---
ax6 = axes[1, 2]
cm = confusion_matrix(y_te_nb, y_pred_nb)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax6,
            xticklabels=labels, yticklabels=labels)
ax6.set_title(f'Naive Bayes Confusion Matrix\n(Acc: {nb_acc*100:.1f}%)', fontweight='bold')
ax6.set_xlabel('Predicted')
ax6.set_ylabel('Actual')

plt.tight_layout()
plt.savefig('model_evaluation_graphs.png', dpi=150, bbox_inches='tight')
plt.show()
print("✅ Graphs saved as model_evaluation_graphs.png")


# ============================================================
# STEP 12: FEATURE IMPORTANCE (Best Tree Model)
# ============================================================
try:
    fi_model = results.get('7. Random Forest', {}).get('model')
    if fi_model and hasattr(fi_model, 'feature_importances_'):
        plt.figure(figsize=(8, 5))
        feat_names = list(X.columns)
        importances = fi_model.feature_importances_
        sorted_idx  = np.argsort(importances)
        plt.barh([feat_names[i] for i in sorted_idx],
                 importances[sorted_idx], color='#2ecc71')
        plt.xlabel('Importance Score')
        plt.title('Feature Importance (Random Forest)', fontweight='bold')
        plt.tight_layout()
        plt.savefig('feature_importance.png', dpi=150, bbox_inches='tight')
        plt.show()
        print("✅ Feature importance plot saved!")
except Exception as e:
    print(f"Feature importance skipped: {e}")


print("\n" + "=" * 60)
print("ALL STEPS COMPLETED SUCCESSFULLY!")
print(f"Best Model : {best_name}")
print(f"R² Score   : {best_row['R2']} ({float(best_row['R2'])*100:.1f}%)")
print("Files saved: best_model.pkl, scaler.pkl")
print("=" * 60)
# ============================================================
# STEP 11: GRAPHICAL ANALYSIS
# ============================================================

print("\n" + "=" * 60)
print("STEP 11: GRAPHICAL ANALYSIS")
print("=" * 60)

import matplotlib.pyplot as plt
import seaborn as sns

# Create large figure
plt.figure(figsize=(18, 12))

# ============================================================
# GRAPH 1: R2 SCORE COMPARISON
# ============================================================

plt.subplot(2, 2, 1)

model_names = []
r2_scores = []

for name, res in results.items():
    if 'R2' in res:
        model_names.append(name)
        r2_scores.append(res['R2'])

sns.barplot(x=r2_scores, y=model_names, palette='viridis')

plt.title("R² Score Comparison")
plt.xlabel("R² Score")
plt.ylabel("Models")

# ============================================================
# GRAPH 2: RMSE COMPARISON
# ============================================================

plt.subplot(2, 2, 2)

rmse_scores = []

for name, res in results.items():
    if 'RMSE' in res:
        rmse_scores.append(res['RMSE'])

sns.barplot(x=rmse_scores, y=model_names, palette='magma')

plt.title("RMSE Comparison")
plt.xlabel("RMSE")
plt.ylabel("Models")

# ============================================================
# GRAPH 3: ACTUAL VS PREDICTED
# ============================================================

plt.subplot(2, 2, 3)

best_predictions = results[best_name]['y_pred']

plt.scatter(y_test, best_predictions, color='blue')

plt.xlabel("Actual Prices")
plt.ylabel("Predicted Prices")

plt.title(f"Actual vs Predicted ({best_name})")

# Perfect prediction line
min_value = min(y_test.min(), best_predictions.min())
max_value = max(y_test.max(), best_predictions.max())

plt.plot(
    [min_value, max_value],
    [min_value, max_value],
    color='red',
    linestyle='--'
)

# ============================================================
# GRAPH 4: ERROR DISTRIBUTION
# ============================================================

plt.subplot(2, 2, 4)

errors = y_test - best_predictions

sns.histplot(errors, bins=30, kde=True, color='green')

plt.title("Error Distribution")
plt.xlabel("Prediction Error")

plt.tight_layout()

# Save graph image
plt.savefig("all_graphs.png")

plt.show()

print("✅ Graphs created successfully!")
print("✅ Graph image saved as all_graphs.png")